# Generated by Django 4.1.3 on 2022-12-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_file_alter_blog_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='file',
            new_name='files',
        ),
    ]
