# Generated by Django 2.2 on 2022-09-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='advertisements_app.Category', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='advertisements_app.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='date_close',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='price',
            field=models.FloatField(default=0, max_length=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Электронная почта'),
        ),
    ]
