# Generated by Django 2.2 on 2022-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_advertisements_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='price',
            field=models.FloatField(max_length=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='views_count',
            field=models.FloatField(blank=True, max_length=100, verbose_name='Колличесво просмотров'),
        ),
    ]
