# Generated by Django 2.2 on 2022-11-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
