# Generated by Django 4.1.3 on 2023-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['title', 'price', 'description', 'shop', 'rest_goods'], 'verbose_name': 'goods', 'verbose_name_plural': 'goods'},
        ),
        migrations.AddField(
            model_name='goods',
            name='rest_goods',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='rest_goods'),
        ),
    ]
