# Generated by Django 4.1.3 on 2023-02-11 03:31

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('last_name', models.CharField(max_length=500, verbose_name='last name')),
                ('date_birthday', models.DateField(verbose_name='date birthday')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'author',
                'ordering': ['name', 'last_name', 'date_birthday'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='isbn')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('date_release', models.DateField(verbose_name='year release')),
                ('pages', models.PositiveIntegerField(verbose_name='pages')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app_books.author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['author', 'title', 'isbn', 'description', 'date_release', 'pages'],
            },
        ),
    ]
