# Generated by Django 4.1.3 on 2023-02-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=64, verbose_name='balance'),
        ),
    ]
