# Generated by Django 4.1.3 on 2023-02-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=64, null=True, verbose_name='balance'),
        ),
    ]
