# Generated by Django 2.2 on 2022-11-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_news',
        ),
    ]
