# Generated by Django 2.2 on 2022-11-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_profile_number_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_news',
            field=models.BooleanField(default=False, verbose_name='Способность публиковать новости'),
        ),
    ]
