# Generated by Django 4.1.3 on 2023-04-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='quantity')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='app_goods.goods', verbose_name='goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sale',
                'ordering': ['pk', 'user', 'goods', 'quantity', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(blank=True, default=0, verbose_name='balance')),
                ('money_spent', models.PositiveIntegerField(blank=True, default=0, verbose_name='money_spent')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['pk', 'user'],
            },
        ),
    ]
