# Generated by Django 2.2 on 2022-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20221108_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Тег'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
