# Generated by Django 2.2 on 2022-11-08 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20221109_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='News', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
